//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProject_S00180206
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowDiscription
    {
        public int Id { get; set; }
        public string Genre { get; set; }
        public int NumberOfSeasons { get; set; }
        public int ViewerCount { get; set; }
        public int ShowId { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
