//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProject_S00180206
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Release { get; set; }
        public string ShowImage { get; set; }
        public int CompanyId { get; set; }
        public int ShowDiscription_Id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ShowDiscription ShowDiscription { get; set; }
    }
}
